"""Initial schema

Revision ID: e2c02a635892
Revises: 
Create Date: 2026-04-27 14:14:28.047865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e2c02a635892'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('file_ref', sa.String(length=511), nullable=False),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=False),
    sa.Column('party_roles', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_user_id'), 'contracts', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('overall_risk_score', sa.Integer(), nullable=False),
    sa.Column('should_sign', sa.String(length=50), nullable=True),
    sa.Column('top_concerns', sa.JSON(), nullable=True),
    sa.Column('top_positives', sa.JSON(), nullable=True),
    sa.Column('negotiating_power', sa.String(length=50), nullable=True),
    sa.Column('power_score', sa.Integer(), nullable=False),
    sa.Column('power_label', sa.String(length=100), nullable=True),
    sa.Column('leverage_points', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_contract_id'), 'analysis_results', ['contract_id'], unique=False)
    op.create_table('clauses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position_index', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('risk_category', sa.String(length=100), nullable=True),
    sa.Column('plain_english', sa.Text(), nullable=True),
    sa.Column('worst_case', sa.Text(), nullable=True),
    sa.Column('financial_exposure', sa.String(length=255), nullable=True),
    sa.Column('negotiable', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('probability', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clauses_contract_id'), 'clauses', ['contract_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('embedding_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_contract_id'), 'embeddings', ['contract_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('pdf_path', sa.String(length=511), nullable=False),
    sa.Column('share_uuid', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_contract_id'), 'reports', ['contract_id'], unique=False)
    op.create_index(op.f('ix_reports_share_uuid'), 'reports', ['share_uuid'], unique=True)
    op.create_table('scan_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_jobs_contract_id'), 'scan_jobs', ['contract_id'], unique=False)
    op.create_table('counter_offers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clause_id', sa.Uuid(), nullable=False),
    sa.Column('aggressive_clause', sa.Text(), nullable=True),
    sa.Column('balanced_clause', sa.Text(), nullable=True),
    sa.Column('conservative_clause', sa.Text(), nullable=True),
    sa.Column('negotiation_email', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counter_offers_clause_id'), 'counter_offers', ['clause_id'], unique=False)
    op.create_table('precedent_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clause_id', sa.Uuid(), nullable=False),
    sa.Column('precedent_summary', sa.Text(), nullable=True),
    sa.Column('enforcement_likelihood', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('cited_cases', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precedent_matches_clause_id'), 'precedent_matches', ['clause_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_precedent_matches_clause_id'), table_name='precedent_matches')
    op.drop_table('precedent_matches')
    op.drop_index(op.f('ix_counter_offers_clause_id'), table_name='counter_offers')
    op.drop_table('counter_offers')
    op.drop_index(op.f('ix_scan_jobs_contract_id'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_reports_share_uuid'), table_name='reports')
    op.drop_index(op.f('ix_reports_contract_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_embeddings_contract_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_clauses_contract_id'), table_name='clauses')
    op.drop_table('clauses')
    op.drop_index(op.f('ix_analysis_results_contract_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_contracts_user_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
